### ISSUE TITLE
Assert output of `make docs` is up to date in CI

### ISSUE THREAD

**Issue by AndrewSisley** [sourcenetwork/defradb#2165]

**Comment by shahzadlone** [comment]
Cheers for opening this! I was actually thinking to add one action [optional / not required] to notify us if our generational steps are out dated:
- mocks (`make mocks`), this one I had started some work on a few months ago.
- docs (`make docs`).
- proto code (cd into net/pb and use the Makefile there).
- mod tidy is clean perhaps (`make tidy`) because just last week I found that out mod tidy command was broken due to a dep issue https://github.com/sourcenetwork/defradb/commit/41581a4debf3f9d97d5c8e3296adb4ef25d3537f
