### ISSUE TITLE
Add support for P2P and ACP 

### ISSUE THREAD

**Issue by shahzadlone** [sourcenetwork/defradb#2366]
~~Implement (and integrate) Defra SourceHub ACP module.~~

There is a bunch of todos in our codebase and temp errors in our codebase preventing ACP from working with P2P.  Resolve them.

https://github.com/sourcenetwork/defradb/issues/2836 has been broken out of this ticket.

**Comment by AndrewSisley** [comment]
Note: This is currently under discussion in the `dev-db.ACP` discord thread: https://discord.com/channels/427944769851752448/1200142876307374100

**Comment by fredcarle** [comment]
<img width="694" alt="Screenshot 2024-04-17 at 12 13 06 PM" src="https://github.com/sourcenetwork/defradb/assets/4949751/22066791-db5e-4c52-bc25-aa31394dc876">

<img width="556" alt="Screenshot 2024-04-17 at 12 13 45 PM" src="https://github.com/sourcenetwork/defradb/assets/4949751/cece2a61-4f52-46e4-8601-99360cca14a5">

**Comment by AndrewSisley** [comment]
note: Unassigning myself for the cooldown, I intend to pick this up again for v0.12, but anyone else is very welcome to steal it in the meantime, or if I am unavailable in 2 weeks.

**Comment by AndrewSisley** [comment]
Bruno is currently working on a new client for SourceHub that will make things much nicer for us from Defra.  It will hopefully be implemented within about 3 weeks.  The new client stuff should not impact the spinning up of SourceHub test instances, so that can be worked on a bit before actually having to worry about writing the production code.  The interface will be defined before he implements it, but working from that too early is risky and may potentially be changed as work on the implementation progresses.

I plan on leaving this ticket for another week or so, before checking in with Bruno RE the status of the new client.
