### ISSUE TITLE
Support for materialized views

### ISSUE THREAD

**Issue by fredcarle** [sourcenetwork/defradb#2951]
We currently have support for non-cached views. We should look into supporting materialized views (views that are static).

**Comment by AndrewSisley** [comment]
Note:

> views that are static

This should not be a requirement, and is probably not desirable at all.  Cache-backed views should be updating automatically as the data backing them (or the view definition) updates. The SIP goes into this a little bit: https://github.com/sourcenetwork/SIPs/blob/sisley/views/x-views/README.md

**Comment by jsimnz** [comment]
It's probably a good first step to just make the views "materialized" meaning static until manually trigger a rematerialization.

Than me can move onto "maintained" (real time) views.

The requirement from Dave/coax is only for materialized views, since that is what they used previously with postgres.
